//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Code/InputSystem/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""PlayerActions"",
            ""id"": ""8b2fff70-5523-47da-b935-293a3e10ae5e"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""56c3744c-3516-451e-b78c-c08584503c05"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Spawn"",
                    ""type"": ""Button"",
                    ""id"": ""60c06a77-b959-45a4-a8d1-b4461229e90d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cell_1"",
                    ""type"": ""Button"",
                    ""id"": ""01481bbb-2d25-4a2b-8991-c99232ee9517"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cell_2"",
                    ""type"": ""Button"",
                    ""id"": ""b935609f-ade3-49f6-aa0a-06cc27777088"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cell_3"",
                    ""type"": ""Button"",
                    ""id"": ""a7d398ba-7729-45fc-ba01-b3b45dec2841"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cell_4"",
                    ""type"": ""Button"",
                    ""id"": ""34b8b5ed-4563-4bdd-ab28-b6af97209be4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cell_5"",
                    ""type"": ""Button"",
                    ""id"": ""a94df3ab-dc9e-4f9c-a2a4-d056e430feb3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cell_6"",
                    ""type"": ""Button"",
                    ""id"": ""1522d045-e71c-4802-aaab-99adf9dbab1f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cell_7"",
                    ""type"": ""Button"",
                    ""id"": ""d176b0bc-a3cd-4c34-959a-85190724c40b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Click"",
                    ""type"": ""Value"",
                    ""id"": ""63cd9c2d-08fa-45af-b99a-0feb0cfe723b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MousePosition"",
                    ""type"": ""Value"",
                    ""id"": ""e9f850f6-d724-4b80-8d27-98bc302c0866"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""501a99b4-9a2c-45a2-8a11-4de47a91a72f"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""423e165b-cba0-42d0-aa85-1d74b8b30d6a"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PlayerScheme"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""d5b10756-6433-4613-9a00-73e615cefb1e"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PlayerScheme"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""51466e16-fcfd-456a-8878-c603013f7aae"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PlayerScheme"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""fc144289-1332-48b4-9939-9929447f3157"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PlayerScheme"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""a29a7b3e-5a4f-48a6-83c7-894c971f0b4e"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Spawn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8c68f069-7144-41d0-9977-2387e61e8f64"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cell_1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cb3c8d34-c243-4037-a8e6-58540923e440"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cell_2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1a568b8c-26aa-43c8-b39c-8ba8945c2de9"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cell_3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a8506974-f121-42ff-b03a-f033eef75cac"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cell_4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5c2403ac-fcfb-4541-9bcc-c9ad7acbb360"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cell_5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0ec2bfea-2ad8-4df7-adff-11061a3c927c"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cell_6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ba9c10d9-603f-466e-94a7-1ee1517de7da"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cell_7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4dad2cff-9d9a-48bb-92ab-dfc4f0572501"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1ac47087-36db-432a-9170-b213f82aa8e6"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MousePosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""SystemActions"",
            ""id"": ""38febae5-93fc-4fd5-b086-1d569da9a718"",
            ""actions"": [
                {
                    ""name"": ""CommunicationStats"",
                    ""type"": ""Button"",
                    ""id"": ""767f88ae-a856-4d1a-8fcf-04eca575da41"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""54dfbb0e-5f5a-4d6a-9b25-4c3c9fba8f0b"",
                    ""path"": ""<Keyboard>/minus"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CommunicationStats"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""PlayerScheme"",
            ""bindingGroup"": ""PlayerScheme"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // PlayerActions
        m_PlayerActions = asset.FindActionMap("PlayerActions", throwIfNotFound: true);
        m_PlayerActions_Movement = m_PlayerActions.FindAction("Movement", throwIfNotFound: true);
        m_PlayerActions_Spawn = m_PlayerActions.FindAction("Spawn", throwIfNotFound: true);
        m_PlayerActions_Cell_1 = m_PlayerActions.FindAction("Cell_1", throwIfNotFound: true);
        m_PlayerActions_Cell_2 = m_PlayerActions.FindAction("Cell_2", throwIfNotFound: true);
        m_PlayerActions_Cell_3 = m_PlayerActions.FindAction("Cell_3", throwIfNotFound: true);
        m_PlayerActions_Cell_4 = m_PlayerActions.FindAction("Cell_4", throwIfNotFound: true);
        m_PlayerActions_Cell_5 = m_PlayerActions.FindAction("Cell_5", throwIfNotFound: true);
        m_PlayerActions_Cell_6 = m_PlayerActions.FindAction("Cell_6", throwIfNotFound: true);
        m_PlayerActions_Cell_7 = m_PlayerActions.FindAction("Cell_7", throwIfNotFound: true);
        m_PlayerActions_Click = m_PlayerActions.FindAction("Click", throwIfNotFound: true);
        m_PlayerActions_MousePosition = m_PlayerActions.FindAction("MousePosition", throwIfNotFound: true);
        // SystemActions
        m_SystemActions = asset.FindActionMap("SystemActions", throwIfNotFound: true);
        m_SystemActions_CommunicationStats = m_SystemActions.FindAction("CommunicationStats", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerActions
    private readonly InputActionMap m_PlayerActions;
    private IPlayerActionsActions m_PlayerActionsActionsCallbackInterface;
    private readonly InputAction m_PlayerActions_Movement;
    private readonly InputAction m_PlayerActions_Spawn;
    private readonly InputAction m_PlayerActions_Cell_1;
    private readonly InputAction m_PlayerActions_Cell_2;
    private readonly InputAction m_PlayerActions_Cell_3;
    private readonly InputAction m_PlayerActions_Cell_4;
    private readonly InputAction m_PlayerActions_Cell_5;
    private readonly InputAction m_PlayerActions_Cell_6;
    private readonly InputAction m_PlayerActions_Cell_7;
    private readonly InputAction m_PlayerActions_Click;
    private readonly InputAction m_PlayerActions_MousePosition;
    public struct PlayerActionsActions
    {
        private @PlayerControls m_Wrapper;
        public PlayerActionsActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_PlayerActions_Movement;
        public InputAction @Spawn => m_Wrapper.m_PlayerActions_Spawn;
        public InputAction @Cell_1 => m_Wrapper.m_PlayerActions_Cell_1;
        public InputAction @Cell_2 => m_Wrapper.m_PlayerActions_Cell_2;
        public InputAction @Cell_3 => m_Wrapper.m_PlayerActions_Cell_3;
        public InputAction @Cell_4 => m_Wrapper.m_PlayerActions_Cell_4;
        public InputAction @Cell_5 => m_Wrapper.m_PlayerActions_Cell_5;
        public InputAction @Cell_6 => m_Wrapper.m_PlayerActions_Cell_6;
        public InputAction @Cell_7 => m_Wrapper.m_PlayerActions_Cell_7;
        public InputAction @Click => m_Wrapper.m_PlayerActions_Click;
        public InputAction @MousePosition => m_Wrapper.m_PlayerActions_MousePosition;
        public InputActionMap Get() { return m_Wrapper.m_PlayerActions; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActionsActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActionsActions instance)
        {
            if (m_Wrapper.m_PlayerActionsActionsCallbackInterface != null)
            {
                @Movement.started -= m_Wrapper.m_PlayerActionsActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_PlayerActionsActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_PlayerActionsActionsCallbackInterface.OnMovement;
                @Spawn.started -= m_Wrapper.m_PlayerActionsActionsCallbackInterface.OnSpawn;
                @Spawn.performed -= m_Wrapper.m_PlayerActionsActionsCallbackInterface.OnSpawn;
                @Spawn.canceled -= m_Wrapper.m_PlayerActionsActionsCallbackInterface.OnSpawn;
                @Cell_1.started -= m_Wrapper.m_PlayerActionsActionsCallbackInterface.OnCell_1;
                @Cell_1.performed -= m_Wrapper.m_PlayerActionsActionsCallbackInterface.OnCell_1;
                @Cell_1.canceled -= m_Wrapper.m_PlayerActionsActionsCallbackInterface.OnCell_1;
                @Cell_2.started -= m_Wrapper.m_PlayerActionsActionsCallbackInterface.OnCell_2;
                @Cell_2.performed -= m_Wrapper.m_PlayerActionsActionsCallbackInterface.OnCell_2;
                @Cell_2.canceled -= m_Wrapper.m_PlayerActionsActionsCallbackInterface.OnCell_2;
                @Cell_3.started -= m_Wrapper.m_PlayerActionsActionsCallbackInterface.OnCell_3;
                @Cell_3.performed -= m_Wrapper.m_PlayerActionsActionsCallbackInterface.OnCell_3;
                @Cell_3.canceled -= m_Wrapper.m_PlayerActionsActionsCallbackInterface.OnCell_3;
                @Cell_4.started -= m_Wrapper.m_PlayerActionsActionsCallbackInterface.OnCell_4;
                @Cell_4.performed -= m_Wrapper.m_PlayerActionsActionsCallbackInterface.OnCell_4;
                @Cell_4.canceled -= m_Wrapper.m_PlayerActionsActionsCallbackInterface.OnCell_4;
                @Cell_5.started -= m_Wrapper.m_PlayerActionsActionsCallbackInterface.OnCell_5;
                @Cell_5.performed -= m_Wrapper.m_PlayerActionsActionsCallbackInterface.OnCell_5;
                @Cell_5.canceled -= m_Wrapper.m_PlayerActionsActionsCallbackInterface.OnCell_5;
                @Cell_6.started -= m_Wrapper.m_PlayerActionsActionsCallbackInterface.OnCell_6;
                @Cell_6.performed -= m_Wrapper.m_PlayerActionsActionsCallbackInterface.OnCell_6;
                @Cell_6.canceled -= m_Wrapper.m_PlayerActionsActionsCallbackInterface.OnCell_6;
                @Cell_7.started -= m_Wrapper.m_PlayerActionsActionsCallbackInterface.OnCell_7;
                @Cell_7.performed -= m_Wrapper.m_PlayerActionsActionsCallbackInterface.OnCell_7;
                @Cell_7.canceled -= m_Wrapper.m_PlayerActionsActionsCallbackInterface.OnCell_7;
                @Click.started -= m_Wrapper.m_PlayerActionsActionsCallbackInterface.OnClick;
                @Click.performed -= m_Wrapper.m_PlayerActionsActionsCallbackInterface.OnClick;
                @Click.canceled -= m_Wrapper.m_PlayerActionsActionsCallbackInterface.OnClick;
                @MousePosition.started -= m_Wrapper.m_PlayerActionsActionsCallbackInterface.OnMousePosition;
                @MousePosition.performed -= m_Wrapper.m_PlayerActionsActionsCallbackInterface.OnMousePosition;
                @MousePosition.canceled -= m_Wrapper.m_PlayerActionsActionsCallbackInterface.OnMousePosition;
            }
            m_Wrapper.m_PlayerActionsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @Spawn.started += instance.OnSpawn;
                @Spawn.performed += instance.OnSpawn;
                @Spawn.canceled += instance.OnSpawn;
                @Cell_1.started += instance.OnCell_1;
                @Cell_1.performed += instance.OnCell_1;
                @Cell_1.canceled += instance.OnCell_1;
                @Cell_2.started += instance.OnCell_2;
                @Cell_2.performed += instance.OnCell_2;
                @Cell_2.canceled += instance.OnCell_2;
                @Cell_3.started += instance.OnCell_3;
                @Cell_3.performed += instance.OnCell_3;
                @Cell_3.canceled += instance.OnCell_3;
                @Cell_4.started += instance.OnCell_4;
                @Cell_4.performed += instance.OnCell_4;
                @Cell_4.canceled += instance.OnCell_4;
                @Cell_5.started += instance.OnCell_5;
                @Cell_5.performed += instance.OnCell_5;
                @Cell_5.canceled += instance.OnCell_5;
                @Cell_6.started += instance.OnCell_6;
                @Cell_6.performed += instance.OnCell_6;
                @Cell_6.canceled += instance.OnCell_6;
                @Cell_7.started += instance.OnCell_7;
                @Cell_7.performed += instance.OnCell_7;
                @Cell_7.canceled += instance.OnCell_7;
                @Click.started += instance.OnClick;
                @Click.performed += instance.OnClick;
                @Click.canceled += instance.OnClick;
                @MousePosition.started += instance.OnMousePosition;
                @MousePosition.performed += instance.OnMousePosition;
                @MousePosition.canceled += instance.OnMousePosition;
            }
        }
    }
    public PlayerActionsActions @PlayerActions => new PlayerActionsActions(this);

    // SystemActions
    private readonly InputActionMap m_SystemActions;
    private ISystemActionsActions m_SystemActionsActionsCallbackInterface;
    private readonly InputAction m_SystemActions_CommunicationStats;
    public struct SystemActionsActions
    {
        private @PlayerControls m_Wrapper;
        public SystemActionsActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @CommunicationStats => m_Wrapper.m_SystemActions_CommunicationStats;
        public InputActionMap Get() { return m_Wrapper.m_SystemActions; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(SystemActionsActions set) { return set.Get(); }
        public void SetCallbacks(ISystemActionsActions instance)
        {
            if (m_Wrapper.m_SystemActionsActionsCallbackInterface != null)
            {
                @CommunicationStats.started -= m_Wrapper.m_SystemActionsActionsCallbackInterface.OnCommunicationStats;
                @CommunicationStats.performed -= m_Wrapper.m_SystemActionsActionsCallbackInterface.OnCommunicationStats;
                @CommunicationStats.canceled -= m_Wrapper.m_SystemActionsActionsCallbackInterface.OnCommunicationStats;
            }
            m_Wrapper.m_SystemActionsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @CommunicationStats.started += instance.OnCommunicationStats;
                @CommunicationStats.performed += instance.OnCommunicationStats;
                @CommunicationStats.canceled += instance.OnCommunicationStats;
            }
        }
    }
    public SystemActionsActions @SystemActions => new SystemActionsActions(this);
    private int m_PlayerSchemeSchemeIndex = -1;
    public InputControlScheme PlayerSchemeScheme
    {
        get
        {
            if (m_PlayerSchemeSchemeIndex == -1) m_PlayerSchemeSchemeIndex = asset.FindControlSchemeIndex("PlayerScheme");
            return asset.controlSchemes[m_PlayerSchemeSchemeIndex];
        }
    }
    public interface IPlayerActionsActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnSpawn(InputAction.CallbackContext context);
        void OnCell_1(InputAction.CallbackContext context);
        void OnCell_2(InputAction.CallbackContext context);
        void OnCell_3(InputAction.CallbackContext context);
        void OnCell_4(InputAction.CallbackContext context);
        void OnCell_5(InputAction.CallbackContext context);
        void OnCell_6(InputAction.CallbackContext context);
        void OnCell_7(InputAction.CallbackContext context);
        void OnClick(InputAction.CallbackContext context);
        void OnMousePosition(InputAction.CallbackContext context);
    }
    public interface ISystemActionsActions
    {
        void OnCommunicationStats(InputAction.CallbackContext context);
    }
}
